### ISSUE TITLE
Describe SG3424P_-_Hack_Zephyr.md

### ISSUE THREAD

**Issue by sampoder** [hackclub/the-hacker-zephyr#1]
Just a one sentence introducing it and a more descriptive file name. @zfogg could you help me with this, I don't really understand the file myself

**Comment by zfogg** [comment]
sure! this is a config file for the tp-link ethernet switches that Dan Eckert let us use. this is actual code to paste via serial terminal.

**Comment by sampoder** [comment]
thanks Zach!!!!
