### ISSUE TITLE
Fix broken CI flow

### ISSUE THREAD

**Issue by zachlatta** [hackclub/the-hacker-zephyr#17]
I believe the CI flow is incorrectly breaking on Markdown links which are valid. We need to either fix the broken links, fix the CI flow, or remove the CI flow so it stops saying the commits are broken.

**Comment by sampoder** [comment]
I vote to remove the CI

**Comment by zachlatta** [comment]
Agreed. Just removed it in https://github.com/hackclub/the-hacker-zephyr/commit/5ef95b7699d1d8d7213cfab4e6a938529b9786a5
